User daemon
Group daemon
Port 8080
PidFile "/var/run/tinyproxy/tinyproxy-novnc.pid"
LogFile "/var/log/tinyproxy/tinyproxy-novnc.log"
Timeout 600
LogLevel Info
StartServers 1
MinSpareServers 1
MaxSpareServers 2
MaxClients 256
DisableViaHeader yes
Allow 0.0.0.0/0
Allow ::/0
ReversePath "/" "http://127.0.0.1:8081/"
ReversePath "/websockify" "http://127.0.0.1:8082/"
ReverseOnly Yes
